<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ManageStudents.aspx.cs" Inherits="ProjectL.ManageStudents" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 400px;
        }
        .auto-style2 {
            width: 131px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="LeftContent" runat="server">
    <asp:Button ID="Button3" runat="server" Text="Back" PostBackUrl="~/AdminDashboard.aspx" />
    <br />
    <br />

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="CenterContent" runat="server">
    <h2>Student Management</h2>
    <p>&nbsp;</p>
    <p>Student search by:</p>
    <p>&nbsp;</p>
    <table class="auto-style1">
        <tr>
            <td class="auto-style2">StudentID:</td>
            <td>
                <asp:TextBox ID="sidTB" runat="server" Width="182px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="auto-style2">Student Name:</td>
            <td>
                <asp:TextBox ID="snameTB" runat="server" Width="182px"></asp:TextBox>
            </td>
        </tr>
    </table>
    <p>
        <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Search" />
    </p>
    <p>&nbsp;</p>
    <p>
        <asp:Label ID="Label1" runat="server" Text="Search Result:" Visible="False"></asp:Label>
    </p>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="GV_RowDeleting">
            <Columns>
                <asp:BoundField DataField="StudentID" HeaderText="StudentID" />
                <asp:BoundField DataField="Name" HeaderText="Name" />
                <asp:BoundField DataField="Branch" HeaderText="Branch" />
                <asp:BoundField DataField="CGPA" HeaderText="CGPA" />
            </Columns>
        </asp:GridView>
    </p>
</asp:Content>
